# Generated by Django 5.0.7 on 2024-08-01 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo_Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=200)),
                ('task_description', models.TextField()),
                ('task_status', models.CharField(choices=[('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Cancel', 'Cancel'), ('Pending', 'Pending')], default='Pending', max_length=100)),
                ('task_deadline', models.DateField()),
                ('task_created_date', models.DateField(auto_now_add=True)),
                ('task_completed', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
